// <auto-generated />
namespace MW_Backend.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addSourceToProductModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addSourceToProductModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201912102226189_addSourceToProductModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
